### ISSUE TITLE
Would it be possible to upgrade to php 8.1?

### ISSUE THREAD

**Issue by luscalopez** [amirsarhang/instagram-php-sdk#2]
This is a great api, could you upgrade to php 8.1? I can help with whatever is needed

**Comment by amirsarhang** [comment]
Thank you, 
Do you have any purpose for doing that? for example is there any issue, with speed, security or anything else?
Because I chose php >=7.0 to increase the coverage of users.

**Comment by luscalopez** [comment]
In this case, it would be because the facebook/graph-sdk package is no longer updated and nowadays many projects are being used laravel 8 or 9, and the current files only allow php 7, I installed your package manually and configured it within the App folder, changing all namespace etc.. everything works fine, but when trying to call the login function it returns this facebook error, the page url is ok
![image](https://user-images.githubusercontent.com/18634690/185997747-5a4bda32-d62c-4757-bc41-82a27a5f3d82.png)

**Comment by amirsarhang** [comment]
[v2.0.0](https://github.com/amirsarhang/instagram-php-sdk/releases/tag/2.0.0) released. 
It's compatible with PHP 8.
